#define PUT "PUT"
#define POST "POST"
#define GET "GET"
#define DELETE "DELETE"
#define SignUp "signup"
#define Login "login"
#define FilmWord "film"
#define Films "films"
#define Followers "followers"
#define Money "money"
#define Published "published"
#define Replies "replies"
#define Comments "comments"
#define Comment "comment"
#define Follower "follower"
#define Buy "buy"
#define Rate "rate"
#define Purchased "purchased"
#define Notification "notification"
#define Read "read"

#define Age "age"
#define Email "email"
#define UserName "username"
#define PassWord "password"
#define Publisher_word "publisher"
#define User_word "user"
#define Year "year"
#define Length "length"
#define Price "price"
#define Summary "summary"
#define Director "director"
#define FilmId "film_id"
#define FilmName "name"
#define MinRate "min_rate"
#define MaxYear "max_year"
#define CommentId "comment_id"
#define Content "content"
#define UserId "user_id"
#define Amount "amount"
#define MinYear "min_year"
#define Limit "limit"

#define Deleted "deleted"
#define Available "available"
#define EmptyString "empty"
#define EmptyInt -1

#define DetailsOfFilm "Details of Film"
#define YearShow "Year"
#define IdShow "Id"
#define DirectorShow "Director"
#define LengthShow "Length"
#define SummaryShow "Summary"
#define RateShow "Rate"
#define PriceShow "Price"
#define CommentsShow "Commnets"
#define RecommendationFilm "Recommendation Film"
#define EqualSpace " = "