#define PUT "PUT"
#define POST "POST"
#define GET "GET"
#define DELETE "DELETE"
#define SignUp "signup"
#define Login "login"
#define FilmWord "film"
#define Films "films"
#define Followers "followers"
#define Money "money"
#define Published "published"
#define Replies "replies"
#define Comments "comments"
#define CommentString "comments"
#define Follower "follower"
#define Buy "buy"
#define Rate "rate"
#define Purchased "purchased"
#define Notification "notifications"
#define Read "read"
#define Readed "readed"
#define UnReaded "unreaded"
#define CommentNotification "comment_notificaion"
#define BuyNotificatoin "buy_notificaion"
#define ReplyNotification "reply_notificaion"
#define RateNotification "rate_notification"
#define FollowNotification "follow_notification"
#define RegisterNotification "register_notification"
#define PublisherShow "Publisher"
#define UserShow "User"
#define WithId "with id"
#define ReplyToYourComment "reply to your comment"
#define RegisterNewFile "register new file"
#define FollowYou "follow you"
#define BuyYourFilm "buy your film"
#define RateYourFilm "rate your film"
#define CommentOnYourFilm "comment on your film"
#define NotificationMessage "Notification Message"

#define Age "age"
#define Email "email"
#define UserName "username"
#define PassWord "password"
#define Publisher_word "publisher"
#define User_word "user"
#define Year "year"
#define Length "length"
#define Price "price"
#define Summary "summary"
#define Director "director"
#define FilmId "film_id"
#define FilmName "name"
#define MinRate "min_rate"
#define MaxYear "max_year"
#define CommentId "comment_id"
#define Content "content"
#define UserId "user_id"
#define Amount "amount"
#define MinYear "min_year"
#define Limit "limit"
#define Score "score"

#define True "true"
#define Dot "."
#define Low 0
#define High 1
#define Vertical " | "
#define Hashtak "#"
#define Space " "
#define USERID "User Id"
#define UserUsername "User Username"
#define UserEmail "User Email"
#define WeakFilm 0.8
#define MediumFilm 0.9
#define StrongFilm 0.95
#define LowInterval 5
#define HighInterval 8

#define Deleted "deleted"
#define Available "available"
#define EmptyString "empty"
#define EmptyInt -1
#define NumberOfShownFilms 4
#define ListOfFollowers "List of Followers"

#define DetailsOfFilm "Details of Film"
#define YearShow "Year"
#define IdShow "Id"
#define DirectorShow "Director"
#define LengthShow "Length"
#define SummaryShow "Summary"
#define RateShow "Rate"
#define PriceShow "Price"
#define Name "name"

#define CommentsShow "Commnets"
#define RecommendationFilm "Recommendation Film"
#define EqualSpace " = "
#define NotSets "not_sets"
#define OK "OK"
#define QuestionMark "?"
#define FilmIdShow "Film Id"
#define FilmNameShow "Film Name"
#define FilmLenghtShow "Film Length"
#define FilmPriceShow "Film price"
#define FilmRateShow "Rate"
#define FilmProductionYear "Production Year"
#define FilmDirector "Film Director"
